# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
