# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170619_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
