# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20170619_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='display',
        ),
    ]
