# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_announcement_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
